version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  web1:
    restart: on-failure
    build: ./web01
    ports:
      - '81:5000'
  web2:
    restart: on-failure
    build: ./web02
    ports:
      - '82:5000'
  nginx:
    build: ./NGINX
    ports:
    - '80:80'
    depends_on:
    - web1
    - web2